Verilog versions of some VHDL examples with their tests
UTN-BA-Sats/cores pull request #20
Opened 2024-03-24 20:57 UTC by AgusGiova

Adding Verilog version of existing VHDL files with their tests. Every test is implemented with some random functions that give random inputs and make the test run a random number of times every time you execute the "make test" command.

The Verilog version that have been added to the core/rtl/examples/comb directory are:
- and.v
- bin2gray.v
- cod_w_prio.v
- comparator.v
- mux_4to1.v
- s_addsub_wo_carry.v

And a python file with a test for each file in the core/tests directory.

2024-03-25 13:31 UTC, lucasliano reviewed
Laburazo Agus. Fijate los comentarios que te dejo. Cualquier pregunta, discrepancia, comentario dejalo escrito por acá y avisame por wpp así lo reviso.

2024-03-25 13:31 UTC, lucasliano commented on rtl/examples/comb/and/and.v
Este archivo está vacio, sacar. Aparte tengo otra pregunta, ¿Por qué se creó otro módulo que se llama Vand?

2024-03-25 13:31 UTC, lucasliano commented on rtl/examples/comb/and/sim.vvp
Sacar todos los archivos .xml, .vvp y .vcd. Podrías agregarlo al gitignore, pero primero sacalos.

2024-03-25 13:31 UTC, lucasliano commented on rtl/examples/ledtest/pinout.pcf
¿Este cambio por qué se hizo? ¿Lo corriste en alguna FPGA?

2024-03-25 13:31 UTC, lucasliano commented on tests/test_Vand.py
> +    iterNumber = random.randint(1,MAX_ITERATIONS)
Que la cantidad de test no sea aleatoria. Poner `for i in range (ITERATIONS)`

2024-03-25 13:31 UTC, lucasliano commented on tests/test_bin2gray.py
> +def verification(dut):
Esta función no tiene mucho sentido. Es mejor poner directamente la condición en el assert para hacer más legible el código. En este caso no se nota mucho porque tenés pocos test por archivo. Pero cuando tengas más archivos puede ser molesto tener que ir a buscar cada función de verificación. De todas maneras no descarto el uso de funciones de verificación, pero tiene que ser un procedimiento más complejo que una sola condición.

2024-03-25 13:31 UTC, lucasliano commented on tests/test_bin2gray.py
> +    if(dut.poBin.value == gray_to_binary(str(dut.piGray.value))): return True
En el `str(dut.piGray.value)` habría que checkear de alguna forma que no te lo tome como válido si te devuelve 'X' o 'Z'

2024-03-25 13:31 UTC, lucasliano commented on tests/test_bin2gray.py
> +    if(dut.poBin.value == gray_to_binary(str(dut.piGray.value))): return True
Igual esto es discutible.. Hacete alguna prueba para ver si hace falta, pero no es tan importante.. Calculo que si viene 'X' o 'Z' te va a dar False el assert de todos modos.

2024-03-25 13:31 UTC, lucasliano commented on tests/test_bin2gray.py
> +    iterNumber = random.randint(1,MAX_ITERATIONS)
De nuevo, que no sea random la cantidad de tests que corren.

2024-03-25 13:31 UTC, lucasliano commented on tests/test_s_addsub_wo_carry.py
> +    iterNumber = random.randint(1,MAX_ITERATIONS)
No random acá

2024-03-25 13:31 UTC, lucasliano commented on tests/test_mux_4to1.py
> +    if(dut.piSel.value == 0 and (dut.poI0.value == dut.piE.value)): return True
Ojo con usar "and" en lugar de "&". En este caso, que comparás de a 1 bit, es lo mismo. Pero si tenés señales más grandes no va a ser lo mismo.

2024-03-25 13:31 UTC, lucasliano commented on tests/test_comparator.py
> +    iterNumber = random.randint(1,MAX_ITERATIONS)
Sacar random

2024-03-25 13:31 UTC, lucasliano commented on tests/test_cod_w_prio.py
> +    iterNumber = random.randint(1,MAX_ITERATIONS)
Sacar random

2024-03-25 13:31 UTC, lucasliano commented on rtl/examples/comb/bin2gray/bin2gray.v
En líneas generales para todos los .v, cambiale los nombres a las señales para cumplir con esta convención #18 (https://github.com/UTN-BA-Sats/cores/issues/18).

2024-03-25 13:31 UTC, lucasliano commented on rtl/examples/comb/bin2gray/bin2gray.v
> +always @(*) begin
Propongo que la lógica combinacional NO se haga adentro de un always. Entiendo que esto es algo que se puede, y que se asemeja más a VHDL. De todas maneras no estoy seguro cual de las dos maneras es una mejor práctica. ¿Tenés algún argumento/referencia para hacerlo de esta manera? ¿Tiene alguna ventaja?

2024-03-25 13:31 UTC, lucasliano commented on rtl/examples/comb/s_addsub_wo_carry/s_addsub_wo_carry.v
Salvo el comentario que te hice en "bin2gray.v", no veo ninguna cosa mala en los verilog. De todas formas, no me puse a analizar la lógica, confío en que está bien hecho con los tests 👍🏽

2024-03-27 15:12 UTC, AgusGiova commented on rtl/examples/comb/and/and.v
Porque no queria pisar ni borrar el test_and.py que ya estaba en la carpeta de test. Ese archivo hacia el test de la and escrita en vhdl. No se si queres que lo borre

2024-03-27 16:22 UTC, AgusGiova commented on rtl/examples/comb/bin2gray/bin2gray.v
> +always @(*) begin
En el tutorial que me habias pasado lo hacia asi. Igual ya lo arregle y los hice todos sin always

2024-04-02 01:26 UTC, lucasliano commented on rtl/examples/comb/and/and.v
Yo dejaría los .vhd pero borrá los tests.

2024-04-02 01:36 UTC, lucasliano requested changes
Hola Agus, solo dos comentarios. 1) Al final se le puede cambiar el nombre Vand.v por and.v? Si podés hacelo, aunque haya que borrar cosas viejas.

2) En el test_s_addsub_wo_carry.py te faltó sacarle el random a la cantidad de test.

Avisame cuando tengas esas pavaditas y metemos el PR.

2024-04-06 01:03 UTC, lucasliano approved these changes
Perfecto Agus

2024-04-06 01:11 UTC, merged